### ISSUE TITLE
Dialogues are cutting off

### ISSUE THREAD

**Issue by Topinas** [Astienth/Cloudpunk-VR#4]
So yeah the dialogues and only those, all other sounds play normally during the cuts, are cutting in and out.

On Flat2VR discord I found someone suggesting that setting game to surround 5.1 and restarting the game fixes it but sadly not for me. Actually went and tried every single options (Mono,Stereo,Quad....) but the issue is there no matter what.

Man I'm itching to play this game so bad! After seeing that cockpit view I fell in love. After I finally figured out the controller I thought I will finally be able to play it but no dice it seems :D  almost thinking of just turning the voices off and playing it without them.

**Comment by Astienth** [comment]
I also had the sound issue but only once or twice. I thought it might have been performance issue. Maybe try to lower down the graphic settings, test at the lowest, see if it does something..?

**Comment by Topinas** [comment]
That is 100% what it was! Even just turning it down to high from maximum fixed the issue completely! I assumed it's not that since the sound otherwise was fine and well I did not mind lower framerate but...yeah.

Man first the controller fixed by just unplugging the second controller. Now this fixed by just turning the graphics down a bit...makes me feel really stupid for not trying this in the first place :D .

Thanks a bunch for the help! Well and for the mod itself as well ofc! Keep up the good work!

**Comment by Astienth** [comment]
I'm so glad it worked ! Depending on which graphic settings you are, you might still experience occasional sound issues but you should be good :)
Thanks for your kind words, it feels good knowing people get to enjoy it !!
